apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: policy-essentials-v2022
  namespace: config-management-system
spec:
  git:
    auth: none
    branch: main
    dir: clusters/cluster2/root/policy-essentials-v2022
    period: 0s
    repo: https://github.com/mikebz/kgr-demo.git
  sourceFormat: unstructured
  sourceType: git
